name        : findutils
version     : 4.4.2
release     : 9
source      :
    - http://ftp.gnu.org/pub/gnu/findutils/findutils-4.4.2.tar.gz : 434f32d171cbc0a5e72cfc5372c6fc4cb0e681f8dce566a0de5b6fccd702b62a
homepage    : http://www.gnu.org/software/findutils
license     : GPL-3.0+
summary     : findutils (basic directory searching utilities)
component   : system.base
description : |
    findutils are basic directory searching tools and are often used with other programs for directory search and file locating.
setup      : |
    %patch -p1 < $pkgfiles/remove-locate.patch
    ./configure --prefix=/usr \
                --libexecdir=/usr/lib/findutils
build      : |
    %make
install    : |
    %make_install
    install -D AUTHORS %installroot%/usr/share/doc/findutils/AUTHORS
    install -D COPYING %installroot%/usr/share/doc/findutils/COPYING
    install -D ChangeLog %installroot%/usr/share/doc/findutils/ChangeLog
    install -D README %installroot%/usr/share/doc/findutils/README
    install -D THANKS %installroot%/usr/share/doc/findutils/THANKS
