name       : findutils
version    : 4.6.0
release    : 11
source     :
    - http://ftp.gnu.org/pub/gnu/findutils/findutils-4.6.0.tar.gz : ded4c9f73731cd48fec3b6bdaccce896473b6d8e337e9612e16cf1431bb1169d
homepage   : http://www.gnu.org/software/findutils
license    : GPL-3.0+
summary    : findutils (basic directory searching utilities)
component  : system.base
description: |
    findutils are basic directory searching tools and are often used with other programs for directory search and file locating.
replaces   :
    - mlocate
setup      : |
    %configure --prefix=/usr \
               --localstatedir=/var/db/locate
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    # To use /var/db/locate
    install -Dm00644 $pkgfiles/findutils.tmpfiles $installdir/%libdir%/tmpfiles.d/findutils.conf
