name       : findutils
version    : 4.7.0
release    : 14
source     :
    - https://ftp.gnu.org/pub/gnu/findutils/findutils-4.7.0.tar.xz : c5fefbdf9858f7e4feb86f036e1247a54c79fc2d8e4b7064d5aaa1f47dfa789a
homepage   : https://www.gnu.org/software/findutils
license    : GPL-3.0-or-later
component  : system.base
summary    : findutils (basic directory searching utilities)
description: |
    findutils are basic directory searching tools and are often used with other programs for directory search and file locating.
replaces   :
    - mlocate
setup      : |
    %configure --localstatedir=/var/db/locate
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    # To use /var/db/locate
    install -Dm00644 $pkgfiles/findutils.tmpfiles $installdir/%libdir%/tmpfiles.d/findutils.conf
