name       : findutils
version    : 4.8.0
release    : 15
source     :
    - https://ftp.gnu.org/pub/gnu/findutils/findutils-4.8.0.tar.xz : 57127b7e97d91282c6ace556378d5455a9509898297e46e10443016ea1387164
homepage   : https://www.gnu.org/software/findutils
license    : GPL-3.0-or-later
component  : system.base
summary    : findutils (basic directory searching utilities)
description: |
    findutils are basic directory searching tools and are often used with other programs for directory search and file locating.
replaces   :
    - mlocate
setup      : |
    %configure --localstatedir=/var/db/locate
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    # To use /var/db/locate
    install -Dm00644 $pkgfiles/findutils.tmpfiles $installdir/%libdir%/tmpfiles.d/findutils.conf
